### ISSUE TITLE
Errors when building vfw nes sample

### ISSUE THREAD

**Issue by est77** [wiz-lang/wiz#103]
vwf.wiz:387: error: `const` declaration with initializer must be inside an `in` statement
vwf.wiz:388: error: `const` declaration with initializer must be inside an `in` statement
* wiz: failed with 2 error(s).

**Comment by Bananattack** [comment]
I couldn't repro this using the latest revision built from source and building the program using the build.bat included in the example folder.

![image](https://user-images.githubusercontent.com/95647/102855356-7f310e00-43f2-11eb-9648-47a1e2f3fef8.png)

What platform are you building with? Can you provide more context about the commandline used to trigger these errors? (Are you attempting to include this module in your own code?) Are you sure Wiz is up-to-date?

the vwf example only builds with recent master revisions of the source, it might not build if you are attempting to use an older version like the current tagged releases on github, or some older from-source installation that doesn't include the compiler changes it depends on.

**Comment by est77** [comment]
I am using linux. I used the build shell script in the vwf directory. My version of wiz is up to date with the main branch on the repo.

**Comment by Bananattack** [comment]
Thanks, the context about the platform was helpful. Spotted the issue. `build.bat` was building `main.wiz` (which is the correct entry point). but the equivalent `build` bash script was incorrectly  building `vwf.wiz` directly, which fails because it depends on being imported from within a program code bank, and would also fail to generate a working nes rom by itself even if it were to compile.

Hopefully that works!

**Comment by est77** [comment]
Yes, I can confirm that works.

**Comment by Bananattack** [comment]
Excellent! Closing the issue, thanks for the report!
