### ISSUE TITLE
Rotate without carry doesn't work on 6502

### ISSUE THREAD

**Issue by veremenko-y** [wiz-lang/wiz#132]
The following code

            a = a >>>> 2;

Generates the error:

            sdk/lib.wiz:169: error: could not generate code for right rotate `>>>>`
            sdk/lib.wiz:169: note: got: `a >>>>= 2`
            sdk/lib.wiz:169: note: expression must be rewritten some other way     
            
            sdk/lib.wiz:169: error: could not generate code for statement

Expected result:

            clc
            ror a
            clc
            ror a

**Comment by Bananattack** [comment]
Currently, Wiz doesn't really support any synthetic operations, with exception of add and subtract. There's this issue on the backlog to eventually allow filling in for these sorts of shifts and rotates: https://github.com/wiz-lang/wiz/issues/94

The code proposed in above is a logical right shift -- it will shift a 0 in for each place moved right, which is incorrect for this operation.  If a logical right shift is desired, there is the `>>>` operator which maps to `lsr a` on the 6502. A true rotate must preserve all bits of the operation, such that repeatedly using the same operation should eventually loop back to the original value.

The code to do an 8-bit right rotate in terms of a 9-bit rotate-with-carry is a bit more complicated: https://wiki.nesdev.com/w/index.php/Synthetic_instructions#8-bit_rotate

Closing this for now since the lack of synthetic operator is a known issue. For now, all shifts and rotates that aren't directly supported on the hardware can use `inline for` loops to cut down on the repetition required. Eventually I would like a way for the language to generate optimal shifts/rotates given the distance of bits required to travel.

**Comment by veremenko-y** [comment]
Yeah. I was assuming I'd get 1:1 assembly operation, not synthetic actual rotate with carry.
