### ISSUE TITLE
Addition with carry is not communicative

### ISSUE THREAD

**Issue by veremenko-y** [wiz-lang/wiz#133]
Simple addition of A with variable is not communicative. See code to reproduce below.

```
in ram {
    var line : u8;
}

in prg {
    line = a = a + line; // pass
    line = a = line + a; // fail

    line = a = a +# line; // pass
    line = a = line +# a; // fail
}
```

**Comment by Bananattack** [comment]
Hmm, this might be a bit unexpected if coming from a higher level language like C. This is by design to allow reasoning about assembly that is generated, and being 1:1 about what was written in the source. I can understand why commuting simple operators like `+` might be nice, but if we do this, I think it could to explode into scope creep of wanting other things to get automatically optimized, and at that point it loses the "assembler" part of the high-level assembler, since it loses guarantees on the code-gen.

Wiz does not re-arrange runtime expressions, or introduce temporaries, or optimize expressions beyond compile-time constant folding. Most binary operators are evaluated in strict left-to-right order. If an binary operator expressions contains a term that is runtime on either side then the whole expression is considered runtime.

If some expression `a = b + c` has no instruction (ie. there is no 3-argument instruction that specifies two sources and one destination), then the compiler is permitted to rewrite this as `a = b; a += c;` to allow it to compile. But I wanted to keep this to a simple fallback on failure that still keeps it in the same order it's written.

`a = a + b + c + d` is evaluated as if it were written `a = (((a + b) + c) + d;`

I didn't want to allow "unspecified order" like in C or C++, this makes it harder to reason about the assembly generated after that point.

If you require evaluation order, you can use parentheses to ensure that a sub-expression is evaluated before another, but if this would require the compiler to store it in a runtime temporary, it is an error. You should rewrite the expression another way: either split into multiple statements, or designate a temporary by nesting an assignment.

---

But, add with carry is definitely not commutative -- carry is a runtime side-effect of some previous instruction, and this requires a strict evaluation order to hold, so these can't be rewritten, and always happen at runtime.

For platforms that actually have RADD/RSUB, not sure what we'd do there, probably introduce an explicit operator if that can't mapped to an instruction in an unambiguous way.
