### ISSUE TITLE
Invalid use of read-modify-write instructions on writeonly memory

### ISSUE THREAD

**Issue by undisbeliever** [wiz-lang/wiz#41]
The following is not valid wdc65816 wiz code (line 9 should be `example_register = aa <<= 1`), but it causes wiz to do something wired and output a strange error message.

```
bank code     @ 0x808000 : [constdata;  0x8000];

extern writeonly example_register @ 0x4300 : u16;

in code {

#[mem16, idx16]
func broken() {
    example_register = aa << 1;
}

}
```

```
`--> ../bin/wiz -o compile_error.sfc compile_error.wiz
* wiz: version 0.1.0 (alpha)
>> Parsing...
>> Compiling...
compile_error.wiz:9: fatal: code needs 51456 byte(s), which exceeds the remaining space in bank `code` by 18691 byte(s)
* wiz: failed with 1 error(s).
```

Also changing `example_register` to `0x2100` causes a different error:
```
 `--> ../bin/wiz -o compile_error.sfc compile_error.wiz
* wiz: version 0.1.0 (alpha)
>> Parsing...
>> Compiling...
compile_error.wiz:8: internal error: write conflict encountered at absolute address 0x808006 while attempting to write byte 0 of 1 byte(s) for code
compile_error.wiz:9: fatal: address was supposed to be reserved here, by code
* wiz: failed with 1 error(s).
```

**Comment by Bananattack** [comment]
This issue is super weird heh. I'll need to look into this more. Does the error only happen for `extern writeonly` registers? or does it happen for `extern var` too? (My hope is it would generate invalid code and no bogus internal write conflicts in that case...)

**Comment by undisbeliever** [comment]
The error also occurs on the 6502 platform and writing to a variable.

```
bank ram  @ 0x0300 : [vardata;    0x500];
bank code @ 0x8000 : [constdata; 0x8000];

in ram {
    var example_variable : u8;
}

in code {

func broken() {
    example_variable = a << 1;
}

}
```

```
`--> bin/wiz -o compile_error_nes.nes compile_error_nes.wiz
* wiz: version 0.1.0 (alpha)
>> Parsing...
>> Compiling...
compile_error_nes.wiz:10: internal error: write conflict encountered at absolute address 0x8006 while attempting to write byte 0 of 1 byte(s) for code
compile_error_nes.wiz:11: fatal: address was supposed to be reserved here, by code
* wiz: failed with 1 error(s).
```

**Comment by undisbeliever** [comment]
Sorry, but this bug is not fixed.

The following is **invalid** wiz code.  It should produce an error.  Instead it outputs an incorrect binary.

This affects both the 6502 and the 65816 platforms.

---
sfc target:
```
bank code     @ 0x808000 : [constdata;  0x8000];

extern writeonly example_register @ 0x4300 : u16;

in code {

const @ 0x80FFFC = reset; // emu reset

#[fallthrough]
func reset() {
    while true {
        mem16();
        #[mem16] {
            example_register = aa << 1;
        }
    }
}

}
```

```
008000 $C2 $20         REP #$20                  A:0000 X:0000 Y:0000 S:01FF D:0000 DB:00 P:16 CYC:7   SL:225 CPU Cycle:147991687
008002 $8D $00 $43     STA $4300 [004300]        A:0000 X:0000 Y:0000 S:01FF D:0000 DB:00 P:16 CYC:13  SL:225 CPU Cycle:147991690
008005 $0E $00 $43     ASL $4300 [004300]        A:0000 X:0000 Y:0000 S:01FF D:0000 DB:00 P:16 CYC:22  SL:225 CPU Cycle:147991695
008008 $80 $F6         BRA $008000               A:0000 X:0000 Y:0000 S:01FF D:0000 DB:00 P:16 CYC:35  SL:225 CPU Cycle:147991703
```
---
nes target:
```
bank code     @ 0x8000 : [constdata;  0x8000];

extern writeonly example_register @ 0x4300 : u8;

in code {

const @ 0xFFFC = reset; // emu reset

#[fallthrough]
func reset() {
    while true {
        example_register = a << 1;
    }
}

}
```

```
8000 $8D $00 $43 STA $4300                       A:00 X:00 Y:00 P:84 SP:FD CYC:199 SL:103
8003 $0E $00 $43 ASL $4300                       A:00 X:00 Y:00 P:84 SP:FD CYC:211 SL:103
8006 $4C $00 $80 JMP $8000                       A:00 X:00 Y:00 P:84 SP:FD CYC:229 SL:103
```

**Comment by Bananattack** [comment]
Hmmm, making sure I understand what the problem is with this now?

I'm not sure I follow what the invalid code is here. It's maybe not as efficient left-shifting the accumulator, but it is valid sequence of instructions that encompasses what the user wrote, isn't it?

Wiz is not allowed allocate implicit temporaries, but it is allowed use the left-hand side to accumulate an calculation. Basically, for any assignment containing a binary operation, Wiz will first try an exact instruction match: `dest = left OP right` and if that isn't found, then Wiz will attempt `dest = left; dest OP= right;` instead. Neither of these forms requires an implicit temporary that isn't already named in the expression, so it is a valid deconstruction to make of the assignment expression.

The code in question `example_register = a << 1;` compiles because `example_register = a` exists and `example_register <<= 1;` also exis---

...

Dohhhhhh I see. Sorry! `writeonly` is getting discarded I missed this. So the remaining issue is that the instruction selection is not respecting `writeonly` constraints, because it is trying use read-modify-write instructions on `writeonly` memory. Going to look into this more!

**Comment by undisbeliever** [comment]
Sorry about it, I should have been clearer.

**Comment by Bananattack** [comment]
No that's okay! Thanks for reporting this. I'll try to investigate a solution. Long weekend in Canada, so crossing fingers to get a chance to do more development stuff, and hopefully clear this out.
