### ISSUE TITLE
Bugs with the wdc65816 platform

### ISSUE THREAD

**Issue by undisbeliever** [wiz-lang/wiz#42]
I'm enjoying wiz so far, but I have noticed the following bugs in the wdc65816 platform.

 * `#:` (bank byte access) seams to be missing.

 * Missing the `WDM` instruction (`WDM` is useful as it can be used as a breakpoint marker in bsnes-plus).

 * The `direct_page` register is the wrong size (it should be a u16).
    ```
    bank code     @ 0x808000 : [constdata;  0x8000];

    in code {

    #[mem16, idx16]
    func no_16bit_pop() {
        direct_page = aa = 0;
    }

    }
    ```

    ```
    `--> ../bin/wiz -o incorrect_direct_page_size.sfc incorrect_direct_page_size.wiz
    * wiz: version 0.1.0 (alpha)
    >> Parsing...
    >> Compiling...
    incorrect_direct_page_size.wiz:7: error: left-hand side of type `u8` cannot be assigned `u16` expression
    * wiz: failed with 1 error(s).
    ```

 * Increment A and Decrement A emit the wrong instructions.

    The following code:
    ```
    config {
        title = "INC DEC A ERROR      ",
    }

    bank code     @ 0x808000 : [constdata;  0x8000];

    in code {

    const @ 0x80FFFC = reset; // emu reset

    #[fallthrough]
    func reset() {
        mem16();
        #[mem16] {
            aa++;
            aa--;
        }
        mem8();
        #[mem8] {
            a++;
            a--;
        }

        while true { };
    }

    }
    ```

    Emits the following binary (Mesen-S trace log):
    ```
    008000 $C2 $20         REP #$20                  A:0000 X:0000 Y:0000 S:01F6 D:0000 DB:00 P:36 CYC:2   SL:0   CPU Cycle:80441748
    008002 $3A             DEC                       A:0000 X:0000 Y:0000 S:01F6 D:0000 DB:00 P:16 CYC:7   SL:0   CPU Cycle:80441751
    008003 $1A             INC                       A:FFFF X:0000 Y:0000 S:01F6 D:0000 DB:00 P:94 CYC:11  SL:0   CPU Cycle:80441753
    008004 $E2 $20         SEP #$20                  A:0000 X:0000 Y:0000 S:01F6 D:0000 DB:00 P:16 CYC:14  SL:0   CPU Cycle:80441755
    008006 $3A             DEC                       A:0000 X:0000 Y:0000 S:01F6 D:0000 DB:00 P:36 CYC:20  SL:0   CPU Cycle:80441758
    008007 $1A             INC                       A:00FF X:0000 Y:0000 S:01F6 D:0000 DB:00 P:B4 CYC:23  SL:0   CPU Cycle:80441760
    008008 $80 $FE         BRA $008008               A:0000 X:0000 Y:0000 S:01F6 D:0000 DB:00 P:36 CYC:27  SL:0   CPU Cycle:80441762
    008008 $80 $FE         BRA $008008               A:0000 X:0000 Y:0000 S:01F6 D:0000 DB:00 P:36 CYC:32  SL:0   CPU Cycle:80441765
    008008 $80 $FE         BRA $008008               A:0000 X:0000 Y:0000 S:01F6 D:0000 DB:00 P:36 CYC:38  SL:0   CPU Cycle:80441768
    008008 $80 $FE         BRA $008008               A:0000 X:0000 Y:0000 S:01F6 D:0000 DB:00 P:36 CYC:43  SL:0   CPU Cycle:80441771
    ```

 * Cannot pop a 16 bit register off the stack.
    ```
    bank code     @ 0x808000 : [constdata;  0x8000];

    in code {

    #[mem16, idx16]
    func no_16bit_pop() {
        aa = pop();
    }

    }
    ```

    ```
    `--> ../bin/wiz -o no-16-bit-pop.sfc no-16-bit-pop.wiz
    * wiz: version 0.1.0 (alpha)
    >> Parsing...
    >> Compiling...
    no-16-bit-pop.wiz:7: error: left-hand side of type `u16` cannot be assigned `u8` expression
    * wiz: failed with 1 error(s).
    ```

 * Finally, I am unable to use an 8 bit Index upon a variable with a 16 bit A.

    I tried to translate the following code to wiz:
    ```
    // Reset all the DMA Registers
    // Registers $4300 - $437f
    a16()
    i8()
        ldx.b   #0x7e
    -
            stz.w   0x4300,x
            dex
            dex
            bpl     -
    ```

    But I am unable to translate the `stz.w 0x4300,x` to wiz code.

    I tried a few different methods, but none of them compile. This one is the closest, it works with a 16 bit index, but not an 8 bit index.
    ```
    bank code     @ 0x808000 : [constdata;  0x8000];

        in code {

        #[mem16, idx8]
        func clear_dma() {
                extern var dma @ 0x4300 : [u8 ; 128];

                x = 0x80 - 2;
                do {
                        *(((&dma as u16) + x) as *u16) = 0;
                        x--;
                        x--;
                } while !negative;
        }

        }
    ```
    ```
    `--> ../bin/wiz -o 8_bit_index.sfc 8_bit_index.wiz
    * wiz: version 0.1.0 (alpha)
    >> Parsing...
    >> Compiling...
    8_bit_index.wiz:11: error: addition `+` is not defined between provided operand types `u16` and `u8`
    * wiz: failed with 1 error(s).
    ```

    Do you have any suggestions, or is this a bug in the platform?

**Comment by Bananattack** [comment]
- `#:` is missing! I thought I added this, but apparently that change was planned but not committed. In the meantime, I think you can take the `far &` address of memory, and then cast that to an `u32` or similar, and shift the bits down and cast to `u8` (something like `((far &myvar as u32) >> 16) as u8)` I think...). This is pretty cumbersome though, definitely need the bank byte access operator.

- `wdm` is missing, I'll try to add support for it soon. For consistency with the debug-breakpoint used in another platforms, I might call it `debug_break();`. In the meantime, you could create a constant with the WDM opcode, and fallthrough into that? It's a pretty crummy workaround but might work.
```
#[fallthrough]
func blahblah() {
  // ...
}
const : u8 = 0x42;
```
(I learned Wiz needs an attribute for `const` to explicitly allow inserting code as constants inside of function blocks, for when you really need to force an exact opcode somewhere, then it'd be possible to wrap some opcode sequences in an `inline func` when they're not supported directly)
- Ouch, it has `inc` and `dec` reversed somehow! I bet 65C02 has the same issue. Hopefully an easy fix in the instruction mapping code.
- I'll need to look into this `pop` issue. (It might need to be split into two intrinsics `push8`/`pop8` and `pop8`/`pop16`, so it can generate the correct opcode, but not sure yet.)
- Arithmetic between different-sized operands is not allowed, currently, because Wiz takes a very reserved approach to mixed sizes / mixed signedness. Implicit widening might require a temporary to hold the upper bits to "expand" the number. (It could probably relax these rules somewhat for unsigned subexpressions, but signed requires a temp to do sign-extension). For the time being, the workaround is to cast 8-bit `x` to a 16-bit unsigned value.

Changing this
```
*(((&dma as u16) + x) as *u16) = 0;
```
to
```
*(((&dma as u16) + x as u16) as *u16) = 0;
```
should work. Unaligned pointer arithmetic is a mess heh.

The reason the assignment can't just be
```
*(&dma as *u16)[x] = 0;
```
is because in "C-style" pointer arithmetic rules, that implies a scaled-index by x (where scale is 2 bytes), because the pointer being indexed is a `*u16` . But the 65816 instruction is unaligned (byte-scale) indexing, not scaled-index. At least on the plus side, the nasty casts call attention to indexing a byte rather than word, but it's a bit of a hassle to fight the type system here and get desired code to compile.

**Comment by Bananattack** [comment]
I've made partial progress on fixing these issues. Here's the current status of this task, as of this message.

Done:

- [x] `debug_break()` and `debug_break(u8)` to emit a 2-byte `WDM` opcode.
- [x] `direct_page` corrected to be `u16`. Now `direct_page = aa;` and `aa = direct_page;` are valid instructions.
- [x] `++a;` and `--a;` opcode mistakes are fixed (65C02 and 65816)
- [x] unaligned 16-bit store already works. `*(((&dma as u16) + x) as *u16) = 0;` should have been `*((&dma as u16 + x as u16) as *u16) = 0;` where both parts are casted to 16-bit integers before doing the addition. It's a bit cumbersome, but it's needed to satisfy the type at the moment.

Remaining:

- [ ] `#:` bank byte-access operator support.
- [ ] 16-bit `push`/`pop` issues.

**Comment by Bananattack** [comment]
I've made partial progress on fixing these issues. Here's the current status of this task, as of this message.

Done:

- [x] `debug_break()` and `debug_break(u8)` to emit a 2-byte `WDM` opcode.
- [x] `direct_page` corrected to be `u16`. Now `direct_page = aa;` and `aa = direct_page;` are valid instructions.
- [x] `++a;` and `--a;` opcode mistakes are fixed (65C02 and 65816)
- [x] unaligned 16-bit store already works. `*(((&dma as u16) + x) as *u16) = 0;` should have been `*((&dma as u16 + x as u16) as *u16) = 0;` where both parts are casted to 16-bit integers before doing the addition. It's a bit cumbersome, but it's needed to satisfy the type at the moment.

Remaining:

- [ ] `#:` bank byte-access operator support.
- [ ] 16-bit `push`/`pop` issues.

**Comment by undisbeliever** [comment]
Thankyou for the quick response.

**Comment by Bananattack** [comment]
Done:
- [x] `#:` bank-byte access operator support. Using the operator will return the third byte of the value (assuming little-endian ordering). Requires a value that is at least 3 bytes in size (or an integer literal that has no size) for the operator to be defined. So `#:` is defined for far pointers, far functions, u24 or larger values, and iexpr.
- ... (see previous post)

Remaining:
- [ ] 16-bit `push`/`pop`

**Comment by Bananattack** [comment]
- [x] 16-bit push / pop. Now 16-bit stack operations use `push16` and `pop16`, and 8-bit stack operations must use `push8` and `pop8`. The push/pop operations that are available depends on the active memory and index modes.

That closes this round of issues with the 65816 backend. Thanks for this report, and feel free to share more bugs if you encounter anything, or features if you have suggestions for making use of the 65816 easier!
