### ISSUE TITLE
Cannot compile a tail call statement on the 65c02 systems

### ISSUE THREAD

**Issue by undisbeliever** [wiz-lang/wiz#62]
The following wiz code does not compile on the 65c02, wdc65c02, rockwell65c02, huc6280 or wdc65816 systems
```
bank prg @ 0x8000  : [constdata; 0x8000];
in prg {

func first_function {
}

const blank_bytes : [u8] = [0 ; 0xff];

func tail_call_test() {
    return first_function();
}

}
```

```
`--> bin/wiz --system=65c02 -o test.bin test.wiz
* wiz: version 0.1.2 (alpha)
>> Parsing...
>> Compiling...
test.wiz:10: error: pc-relative offset is outside of representable signed 8-bit range -128..127
* wiz: failed with 1 error(s).
```

**Comment by Bananattack** [comment]
Hmm, with this one, is it possible to prefix a `^` in front of the return? This would make the jump to a further away label.

In 65c02 and onward, the backend will prefer `bra` over `jmp` once it is available. The backends are designed to use the smallest possible branch instruction size first, and will prefer relative jumps over absolute jumps when possible. The same limitation exists in Z80 land (eg. msx, game gear, etc) and GB too, but there they use `jr` for jump relative and `jp` for jump absolute, ROM is at 0x0000.

Unfortunately, I couldn't think of a good rule for it to automatically select the next size up without a cascading effect, but it maybe could do something for backwards jumps. Forward jumps are tricky, because the assembler needs to assume a size during its first pass over the IR so that sizes and labels are correctly reserved, and the next pass can write the instructions with known values. Assuming the smallest size at least ensured no implicit absolute jumps were put in code expecting relative jumps, But tail calls are kind of strange case.

**Comment by undisbeliever** [comment]
Using a `^return` gives me the same error.

```bank prg @ 0x8000  : [constdata; 0x8000];
in prg {

func first_function {
}

const blank_bytes : [u8] = [0 ; 0xff];

func tail_call_test() {
    ^return first_function();
}

}
```
```
`--> bin/wiz --system=65c02 -o test.bin test.wiz
* wiz: version 0.1.2 (alpha)
>> Parsing...
>> Compiling...
test.wiz:10: error: pc-relative offset is outside of representable signed 8-bit range -128..127
* wiz: failed with 1 error(s).
```
